[WIP] Add Guid type hiding raw ibv GUID
jonhoo/rust-ibverbs pull request #16
Opened 2021-08-22 16:01 UTC by planetA

Create new Guid type that takes care of endianness conversion.

2021-08-31 19:04 UTC, planetA commented on src/lib.rs
> +    fn is_nil(&self) -> bool {
IBTA 4.1.1 6) says:

> The unicast GID address 0:0:0:0:0:0:0:0 is reserved - referred to as
> the Reserved GID. It shall never be assigned to any endport.

2021-09-02 00:08 UTC, jonhoo commented on src/lib.rs
> +        let padded = vec![
`u32` seems like the right choice, yeah!

2021-09-02 00:09 UTC, jonhoo commented on src/lib.rs
> +    fn is_nil(&self) -> bool {
In that case, how about calling this `is_reserved`, with documentation that includes that quote from the spec?

2021-09-25 20:09 UTC, jonhoo requested changes
Looking better! I left a few more inline comments.

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +        u32::from_be_bytes(padded.try_into().unwrap())
This should not be a `vec!`, but instead just an array directly:
```suggestion
        let padded = [
            0,
            self.raw[0],
            self.raw[1],
            self.raw[2],
        ];
        u32::from_be_bytes(padded)
```

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +    fn oui(&self) -> u32 {
This should be `pub`, otherwise callers can't access it. That will also let you remove the `#[allow(dead_code)]`.

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +    fn is_reserved(&self) -> bool {
```suggestion
    pub fn is_reserved(&self) -> bool {
```

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +    fn is_reserved(&self) -> bool {
It'll also need some documentation

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +        self.raw.iter().all(|i| *i == 0_u8)
Does
```suggestion
        self.raw == [0; 8]
```
work?

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +        u64::from_be_bytes(guid.raw[..].try_into().unwrap())
Does this not work?
```suggestion
        u64::from_be_bytes(guid.raw)
```

2021-09-25 20:09 UTC, jonhoo commented on src/lib.rs
> +
Why is this impl needed?

2021-11-10 02:05 UTC, jonhoo commented on ibverbs/src/lib.rs
> +    /// a 24-bit number inside a u64 number.
```suggestion
    /// a 24-bit number inside a u32.
```
I think this is what you mean?

2021-11-10 02:06 UTC, jonhoo approved these changes

2021-11-10 02:06 UTC, jonhoo commented on ibverbs/src/lib.rs
> +    /// reserved.
```suggestion
    /// Returns `true` if this GUID is all zeroes, which is considered reserved.
```

2021-11-10 02:06 UTC, merged

2021-11-10 02:06 UTC, jonhoo commented
Thanks!