Make the Endpoint fields accessible and the Gid optional
jonhoo/rust-ibverbs pull request #26
Opened 2024-01-18 13:35 UTC by YtvwlD

I do have an existing C application I want to communicate with and I think it's not using global routing, so I have to get the (lid, qpn) information out of this library and into the other application (and back).

Because `QueuePairEndpoint` is already `Serialize` and `Deserialize`, I don't think, making the fields public has any serious implications (though adding getter functions and a `new` function might be nicer, idk).

2024-01-20 09:05 UTC, jonhoo requested changes
Seems reasonable to me! Just a few smaller bits:

2024-01-20 09:05 UTC, jonhoo commented on ibverbs/src/lib.rs
>      /// ah_attr.grh.hop_limit = 0xff;
I think this should then also be removed?

2024-01-20 09:05 UTC, jonhoo commented on ibverbs/src/lib.rs
> +    /// If the endpoint contains a Gid, the routing will be global.
Let's also write out what the implication is of this in terms of what fields will be set on `ah_attr`.

2024-01-20 09:13 UTC, jonhoo commented
Looks like rustfmt also [isn't happy](https://github.com/jonhoo/rust-ibverbs/actions/runs/7593405746/job/20683850564?pr=26#step:4:22) with this line:

https://github.com/jonhoo/rust-ibverbs/blob/53e1782306ab67ff786a0ac9391fffd070c47702/ibverbs/src/lib.rs#L1410

2024-01-24 20:45 UTC, YtvwlD commented
Good points. I've modified the documentation and the line in the test.

2024-01-28 13:52 UTC, jonhoo approved these changes
Looks good to me, thanks!

2024-01-28 13:55 UTC, merged

2024-01-28 13:56 UTC, jonhoo commented
Released as 0.7.1 :tada: